### ISSUE TITLE
Not working for me.. Help please?

### ISSUE THREAD

**Issue by sametgs70** [UraraReika/jet-woo-builder-products-grid-custom-fields#1]
Hi,

I love the work, i am able to upload the plugin but when i place the folder in the child theme, or normal theme it breaks down my site and i get a critical error.

Its not working, and i would love to have some help with this

**Comment by UraraReika** [comment]
Hello @sametgs70 !

This problem occured due to old jet-woo-builder template. We updated it and now everything should be okey.
