### ISSUE TITLE
Meta data doesn't show up

### ISSUE THREAD

**Issue by NarfArf** [UraraReika/jet-woo-builder-products-grid-custom-fields#2]
Followed the readme, installing plugin and copying jet-woo-builder to child theme. 

The new options for returning meta data in categories grid show up, but no meta data shows up, even if data exists in database at the exact field.

Can provide testing credentials if needed.

![image](https://user-images.githubusercontent.com/17137821/191940584-773e78ab-45e5-4647-840d-3accb6f0523c.png)

**Comment by UraraReika** [comment]
Hello @NarfArf !

We have checked your request and everything seems to be working correctly. Perhaps this is related to your site. Please contact Crocoblock support team. They will help with your issue with this plugin.

Thank you!
