### ISSUE TITLE
I can't get this to work.

### ISSUE THREAD

**Issue by dan-loffler** [UraraReika/jet-woo-builder-products-grid-custom-fields#3]
Hi, I put the folder into my child theme. I have a taxonomy called Brands. But I have tested with Product Price, and many other fields, and can't get anything to show. Thanks! - Dan

![Screenshot_1](https://github.com/user-attachments/assets/61c4f37e-5666-472c-989c-9adbf00b05c0)

**Comment by UraraReika** [comment]
Hello @dan-loffler ! Thank you for your feedback!

Originally this fields - https://tppr.me/3kQi6l have no dynamic functionality so i assume you added it by yourself. If it wasn't added from the start then it means it will not work properly. In key field you should put product meta key. But you used dynamic tags that already wants to return field value and not the key of the value that is why you get nothing on the frontend.

Please [contact](https://support.crocoblock.com/support/home/ ) our support team to get more help.

Thank you for your understanding.
